/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CriarCasoRouteImport } from './routes/criar-caso'
import { Route as IndexRouteImport } from './routes/index'

const CriarCasoRoute = CriarCasoRouteImport.update({
  id: '/criar-caso',
  path: '/criar-caso',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar-caso': typeof CriarCasoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar-caso': typeof CriarCasoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criar-caso': typeof CriarCasoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/criar-caso'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/criar-caso'
  id: '__root__' | '/' | '/criar-caso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriarCasoRoute: typeof CriarCasoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/criar-caso': {
      id: '/criar-caso'
      path: '/criar-caso'
      fullPath: '/criar-caso'
      preLoaderRoute: typeof CriarCasoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriarCasoRoute: CriarCasoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
