/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CriarCasoRouteImport } from './routes/criar-caso'
import { Route as ExecutarCasoRouteImport } from './routes/executar-caso'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarCasoRoute = CriarCasoRouteImport.update({
  id: '/criar-caso',
  path: '/criar-caso',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutarCasoRoute = ExecutarCasoRouteImport.update({
  id: '/executar-caso',
  path: '/executar-caso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar-caso': typeof CriarCasoRoute
  '/executar-caso': typeof ExecutarCasoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar-caso': typeof CriarCasoRoute
  '/executar-caso': typeof ExecutarCasoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criar-caso': typeof CriarCasoRoute
  '/executar-caso': typeof ExecutarCasoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/criar-caso' | '/executar-caso'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/criar-caso' | '/executar-caso'
  id: '__root__' | '/' | '/criar-caso' | '/executar-caso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriarCasoRoute: typeof CriarCasoRoute
  ExecutarCasoRoute: typeof ExecutarCasoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-caso': {
      id: '/criar-caso'
      path: '/criar-caso'
      fullPath: '/criar-caso'
      preLoaderRoute: typeof CriarCasoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executar-caso': {
      id: '/executar-caso'
      path: '/executar-caso'
      fullPath: '/executar-caso'
      preLoaderRoute: typeof ExecutarCasoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriarCasoRoute: CriarCasoRoute,
  ExecutarCasoRoute: ExecutarCasoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
